version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: on-failure

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: on-failure

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        WP_COMMOM_USER: ${WP_COMMOM_USER}
        WP_COMMOM_USER_EMAIL: ${WP_COMMOM_USER_EMAIL}
        WP_COMMOM_USER_PASS: ${WP_COMMOM_USER_PASS}
        WP_ADM: ${WP_ADM}
        WP_ADM_EMAIL: ${WP_ADM_EMAIL}
        WP_ADM_PASS: ${WP_ADM_PASS}
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge